server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/knikhilr/scf-config-repository.git
  application:
    name: configserver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
    